### PR TITLE
fix(schema/Task): 为 TaskSchema 补充字段

### PR DESCRIPTION
**Pull request by chuan6**
- [x] ancestorIds
- [x] _taskId
- [x] storyPoint
- [x] workTime
- [x] parent
- [x] tags
- [ ] ~ancestors~
- [ ] ~subtasks~

### CODE REVIEW

**Comment by Brooooooklyn** [comment]
see https://github.com/teambition/teambition-sdk/pull/267/commits

**Comment by chuan6** [comment]
@Brooooooklyn [泪目] 👍

**Comment by chuan6** [comment]
@Brooooooklyn 嗯，是的，都改过来了。谢谢

**Comment by bjmin** [comment]
LGTM

**Comment by chuan6** [comment]
@Saviio 你有空帮我看一下这个 PR 吧，谢谢 :)

**Comment by chuan6** [comment]
@bjmin 谢谢 👍

**Pull request merged**
